# Generated by Django 4.2.13 on 2024-05-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='F1 blog', max_length=255),
        ),
    ]
