# Generated by Django 4.2.13 on 2024-06-01 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_catagory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catagory',
            new_name='Category',
        ),
    ]
